// Auto-generated by generate_backgrounds.py — do not edit manually

import bg_ice_cream_sandwich from './assets/bg_ice_cream_sandwich.webp';
import bg_cereal_milk from './assets/bg_cereal_milk.webp';
import bg_glazed_cinnamon_roll from './assets/bg_glazed_cinnamon_roll.webp';
import bg_caramel_popcorn from './assets/bg_caramel_popcorn.webp';
import bg_chocolate_milkshake from './assets/bg_chocolate_milkshake.webp';

export const BACKGROUNDS = {
  ice_cream_sandwich: bg_ice_cream_sandwich,
  cereal_milk: bg_cereal_milk,
  glazed_cinnamon_roll: bg_glazed_cinnamon_roll,
  caramel_popcorn: bg_caramel_popcorn,
  chocolate_milkshake: bg_chocolate_milkshake,
};
